image: nixos/latest
sources:
  - https://git.sr.ht/~cyplo/blog

secrets:
  - b7161fff-05f4-4470-b4a1-57bd67dede23
  - 47d167ed-ef43-4515-9923-6954d34a4fab

tasks:
  - github_push: |
      set +xv
      cd blog
      GITHUB_TOKEN=`cat ~/.github_token`
      git remote add github https://cyplo:$GITHUB_TOKEN@github.com/cyplo/blog.git
      git push github master
  - publish: |
      set +xv
      cd blog
      NETLIFY_TOKEN=`cat ~/.netlify_token`
      nix-shell -p hugo --run 'hugo --gc --minify'
      nix-shell --run 'netlify-deployer `git branch --show-current` 7a0944f0-cfd0-424b-8252-ca44fc950350 public'
