image: nixos/latest
sources:
  - https://git.sr.ht/~cyplo/blog

secrets:
  - b7161fff-05f4-4470-b4a1-57bd67dede23
  - 47d167ed-ef43-4515-9923-6954d34a4fab

tasks:
  - github_push: |
      set +xv
      cd blog
      GITHUB_TOKEN=`cat ~/.github_token`
      git remote add github https://cyplo:$GITHUB_TOKEN@github.com/cyplo/blog.git
      nix-shell --pure --run 'git push github --all --force'
  - publish: |
      set +xv
      cd blog
      nix-shell --pure --run 'hugo --gc --minify'
      export NETLIFY_TOKEN=`cat ~/.netlify_token`
      if [ `git branch --contains HEAD | grep -i master` ]; then nix-shell --pure --keep NETLIFY_TOKEN --run 'netlify-deployer master 7a0944f0-cfd0-424b-8252-ca44fc950350 public'; fi
