language: python
python: 3.5
sudo: true
dist: trusty
install:
- "./travis/install-requirements"
script:
- "./travis/build"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  repo: cyplo/cyplo.github.io
  target-branch: master
  verbose: true
  local-dir: output
  on:
    branch: master
env:
  global:
  - secure: YQnRjki73U7rtJo4PRpiwtzpHUJ1PN9/slQEqBWGPV1WKIMcnwju0D3rlUzwf9oD5Iehe7TQftP19KDDHbTyIXnFbJsiPw0nLD0RXKLe9cHEI0xi+KWHTBF7/lXdyW6eOaSGOrR+2bJVDz+hwr5JOgUhwclz7bdvYGRT0g7Je/aeIa0oZNyGfgl7i9v8+pxpftXwuzbQEcg82Brjc2IxKA7m7vdTd7RdONe0zIQgog/6qdrDrbc9ctWFD/pjTWOtpFOyWGqWUS5j/8k1NorI3NDrj3bW1k+W4c4R8dX+/olRdiBWj0SzwOEHTVK+QRN/SHLUuDjyDX2IJ3QkpUn532dFBIChbKHWol0ZLM9otrc3AJV21A6OgmytC2JzXZWNHyaOnetvjJ1YQSb8iIWiCPSEbqsrIuDHdbCi6IFNzB0kGzA+fdNKyB0AuB3DNBfcevs+I0lsOXac1Xu0aFyz8vpLAF1mJL6dXmGBPKWZEXwLEhTBHxyPLfwPndrakGe3OR/e6M7N2Su0E02gW/T1J1HajtL5O+rR0FdyrQyMFL5IQ7rhHDS1Co+2f6FTX5w6xl+iHMo+wNvPS15+HMsCgKKZmU7CUolDRdYHRnIkn+ede/OvnulO0hGlQK7savikvMKZoxS2ztzbQnNkMG5SawRcnGgC5dPpieit7bU4E/Y=
