language: python
python: 3.5
sudo: true
dist: trusty

install:
    - "./travis/install-requirements"
script:
    - "./travis/build"
deploy:
    - provider: script
      script: ./travis/deploy.sh
      on:
        - master
        - s3

env:
  global:
  - secure: GRm8uLPX+tyE9NKV6nfCEgV2HlQyHVrNsYBjI3A1OeOBhmyCc8Mjww9UjcJ+/A7BffMWD7es2etZrjwB0qs98I2cC6AuuSXr80483NWC46luNjcsyHFt0DsvkhzMJ4RvA6p50ILJpON7aFr3R4X2IXIeIcKCQEBmu9398WxwT2xCTsTJimHPT9vAxMhdP5tq5BVVuWjWLJc8zIVlxR2yaXzvzpayxVO85h5HuJ2ef/nqnMbdr6XJxidBp1Qz9/liWxa877yfoFgxysJKkuT1UkfmB37e78uaA7sXPCkrTn4zD/OxExGoGPW4LTOz/Q2rPFtbmTM9tB9WXVkzIBafXECdYyIPfR4PMV+2p8b6vuVznpFZfDI6edDummuAJ8DEpD6XZ9SMi3h9mFBSxf6SO3OyeWlICd49vRxQNqCE1tMSiGjnk54N7nv42M/SsIdN0hHxJzEIz9yYkaorREj7MFbszlTmaRmnH0fWY98B9o+t0sSFRBkc1jZ9E7L+mnr4Z5NE7GZrktHAx9HnTlV5gVSZ+FBf6LmHiYoLAnht7ek/G4rktWTdIjIeZAzfLbNBDDmVENIUImEMxlzF/mm9RiXOq+kdc4DivRryx84D3AJTyUzEkv1HUnmkmXdNIEqt6fv1LszAuRoJ+NgGnKnzlCFvPoqhNrKbg0/G1btwPBc=
  - secure: XcBDSyfxhvskDkrOoN+3OBqzqtXj0TXDfd5v9G+Rnpu8rNH1MtE0EkNT9vJebDXO2dExJ53RWchSt84opZHYcwYCIzuUwdjJaKLl8AaB3+2/gS+ez2LpseU9Gv4geV/xRTXrTAxzGta6a3Uk75B4X2mQ3mn8A+vNWJgLYgyDbIXAg1CxVoTI3VdpuHFujYNUCgwZBW2QywDoWbYLTZWxl5CdhRwgADu1wHJUBhPqaoqJQW36DnphSPDbwNZiMZYQkdLroN3dMoxWZbmm8TXad/dLBzOMVcdPRmIGkpxs07NqJiY9+5K3B8ug5A4Dogl/trRdK0X3w2cNXe/5sED3iaDsa1jKt/FDNpTf0OnJpJCHb2G1bcOApYG6yMbdG2c8YUvKMPH/37K4g1wYP5OAIYeMsEefURCJ+NnL8Tl9LvEAEZ11VMtB3ip0oTHfT1CLBfuyDkqAnRNRuRe2AAKrWip9Sf/Fy5vdtOoVadM0GyP1poQ6EI4cqx71RqN1VdyVardFSFBafYKtZw69yOaR39qgE2ww1Euq1hIMDEPkuF8fQAFYsGzHi5C+mlMhZ+v9OuRT3B+c2r25QVf8QDQKNNE6+TQZIWQ7Eshn4YaoA//smxWaLTy6I330SUrqmZJdzIybGVVIG/wtGfFu/aKNUckOzEooX+wvXkyQn1RqB6E=
