language: python
python: 3.5
sudo: true
dist: trusty

install:
- "./travis/install-requirements"

script:
- "./travis/build"

deploy:
  provider: s3
  access_key_id:
      secure: "UKCJPsPeC7gfmPPEGFMBZYXs7vbONmC/oGzqKA9e+apL6ME25Xw6ihDbi1+kAKbtZZxe0yPii8AQ2Jg7dprVdUo9568f4PpYvUOiWhprskzx1/hiQEuz19U5U9ez6FkFFdiRL0YJRMuo9PRcRCHaQuDsT2trb58pxNMnCG0rzzlxKgQ58GEnBarE81HZxlmZATXyaqUaEOcCkrR60LzPi4QVJ4cSW7qoPoZKs6kZqGa0us2SxVwcx13BRb4F61OdKb6OtkNXEDiN3/D0WSiJ5yPoXKjDsyNtcTNSuGAp8osk8EhEkLY2tEh7m4WC+ZHIB89Zinv0VqExTpEut/0IgNY8680+j3lHYj0U6zz7SgrcJAv2qOsDcOAY+WZYq2VW0PQxK/vwN1Tkmr0s7sSWNJSkiUC1iSM2Jrs9kcKW7mYzFmCI6wjtGmZ2wNCYfUwHvNT64pf1BSQacSty5C+68RDX5RKZArG6iJzxgKNQAckLdnOF/TZroJwhbTmqEbAsrANtvgAMFl9b+p+14f1BzaRWkxlJdEht0z5wckd/ctYNDLD1x0AKHhQyX6wazyfUsbM7jLDKFBz3Q0EVtiGqD4ps1FsEofb3MTDJMRr3Ysos7mxYuVQ6jLJWk26Xs3FT3DQGbeArF6BNXBPKLTLPljKzRPqaPPmPIHM+ZSYc3Es="
  secret_access_key:
    secure: "ADAsxY3KvFmZfC3O28z3teOsgH09TTOp6s43+v/AICPmMucmhNNRxg42qtZO962Np/80sMm49DPSGWXm9z/D81iqI2rXjCiU6jiTdjMqNfyZCa6BwmfNam9rVsZKGxw27IhJx1YEzmFIarfSr/3DQXHJ6BnzdESo9XyExMGrDcJozE3zQ83YdFMhSdyKMDtLfGFr4ObOZXjKikPr5MBW7zJiUe3vdCLejiSHrRvVJX7D179PAFaUDrhfYxjR1ILMZWQkw3GvwWrfiW63oTKfpq90iAIk5qarGw3n4us8tqImuyB0y9T5GZrrAEKdnXIZwZmB5Ld7oxNf7mBaZ3q3awYzWoMzJAPmbv3KOO4TwLzqzqRhXUVSCi1dKWeaGPwpcKrQxoBGnp0HfXvh6R15veAB0hwsOD/ps6ivWNl3TaAbjDkIVt5ysvXzbRJDXffEphOuHhM+hbzTEP7dw7u8rf4DDu4lqrHxXD9NRtzRSn1KsTq9CWkaKFJZBCuvKmHmnCCdfLxmOuJi40JKPLvAXx5Yf+x+5UUPEa8dhZytmAz9hYdVH7DdEnK54WTm7afcn0QPt6+Jcuc1CSuRPSurmKxrUHwbEcOoBcaBQd8kJ6nUAC8Z33pCXZcMk/9YSeSUGAoTD/1QHfIAtzhT1Vd73GRSvwYPF+pjJ4oHVupQZws="
  bucket: blog.cyplo.net
  local-dir: output
  acl: public_read
  skip_cleanup: true
  on:
      branch:
          - master
          - s3
