#!/bin/bash
set +e
echo "Adding git remote"
git remote add origin https://github.com/cyplo/blog.cyplo.net.git 
echo "Starting LFS pull"
git lfs pull
git lfs ls-files
set -e
ls -hal files/hosted/
echo "Build starts"
nikola build
