baseurl = "https://blog.cyplo.dev/"

languageCode = "en-gb"

theme = "beautifulhugo"
paginate = 7

pygmentsUseClasses=true
pygmentsCodeFences=true

title = "Adventurous Computing"

[taxonomies]
series = "series"
tags = "tags"

[[params.bigimg]]
src = "images/header.jpg"
position = "center top"

[params]
homeTitle = "Adventurous Computing by Cyryl Płotnicki"
keywords = "programming, testing, tdd, rust, golang"
logo = "images/avatar.jpg"
showRelatedPosts = true
rss = true
selfHosted = true

[[menu.main]]
identifier = "about"
name = "about"
url = "/pages/about"
weight = 1

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "donate"
name = " donate"
url = "https://liberapay.com/cyplo/"
weight = 3

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/pages/projects"
weight = 4

[[menu.main]]
identifier = "talks"
name = "talks"
url = "https://slides.cyplo.dev/"
weight = 5

[[menu.main]]
identifier = "git"
name = "git"
url = "https://git.cyplo.dev/explore/repos"
weight = 6

[Author]
name = "Cyryl Płotnicki"
website = "https://blog.cyplo.dev/"
email = "blog@cyplo.dev"
github = "cyplo"
gitlab = "cyplo"
twitter = "cyplo"
linkedin = "cyplo"
mastodon = "peninsula.industries/@cyplo"
