baseurl = "/"

languageCode = "en-gb"

theme = "beautifulhugo"
paginate = 16

pygmentsUseClasses=true
pygmentsCodeFences=true

[[params.bigimg]]
    src = "img/header.jpg"
    position = "center top"

[languages]
  [languages.en]
    title = "Adventurous Computing by Cyryl Płotnicki"
    keywords = "programming, testing, tdd, rust, golang"
    logo = "img/avatar.jpg"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "donate"
        name = " donate"
        url = "https://liberapay.com/cyplo/"

      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/posts"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/pages/about"

      [[languages.en.menu.main]]
        identifier = "files"
        name = "files"
        url = "/pages/files"

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/pages/projects"
