baseurl = "https://blog.cyplo.net"
title = "Adventurous Computing"

languageCode = "en-us"
theme = "m10c"

[params]
    email = "blog@cyplo.net"
    author = "Cyryl Płotnicki"
    description = """
    I like to write about technology, people and what happens when they intermix.
    """

[[params.social]]
    name = "heart"
    url = "https://liberapay.com/cyplo/"
[[params.social]]
    name = "mail"
    url = "mailto:blog@cyplo.net"
[[params.social]]
    name = "github"
    url = "https://github.com/cyplo"
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/cyplo"