baseurl = "/"

languageCode = "en-gb"

theme = "beautifulhugo"
paginate = 16

pygmentsUseClasses=true
pygmentsCodeFences=true

title = "Adventurous Computing"

[taxonomies]
    series = "series"

[[params.bigimg]]
    src = "img/header.jpg"
    position = "center top"

[params]
    homeTitle = "Adventurous Computing by Cyryl Płotnicki"
    keywords = "programming, testing, tdd, rust, golang"
    logo = "img/avatar.jpg"
    showRelatedPosts = true
    rss = true

[[menu.main]]
identifier = "donate"
name = " donate"
url = "https://liberapay.com/cyplo/"

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts"

[[menu.main]]
identifier = "about"
name = "about"
url = "/pages/about"

[[menu.main]]
identifier = "files"
name = "files"
url = "/pages/files"

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/pages/projects"

[Author]
  name = "Cyryl Płotnicki"
  website = "blog.cyplo.dev"
  email = "blog@cyplo.dev"
  github = "cyplo"
  gitlab = "cyplo"
  twitter = "cyplo"
  linkedin = "cyplo"