baseurl = "https://blog.cyplo.net"

languageCode = "en-gb"

theme = "terminal"
paginate = 7

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Adventurous Computing by Cyryl Płotnicki"
    subtitle = "I like to write about technology, people and what happens when they intermix."
    keywords = "programming, testing, tdd, rust, golang"
    copyright = "2010-2019 Cyryl Płotnicki"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Adventurous Computing by Cyryl Płotnicki"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "donate"
        name = " donate"
        url = "https://liberapay.com/cyplo/"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/pages/about"

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/pages/projects"

[[params.social]]
    name = "github"
    url = "https://github.com/cyplo"
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/cyplo"