baseurl = "https://blog.cyplo.net"
title = "Cyryl Płotnicki"

languageCode = "en-us"
theme = "m10c"

author = "Cyryl Płotnicki"
description = "Adventurous Computing"
copyright = "© Copyright 2010-2019 Cyryl Płotnicki"

[params]
  email = "blog@cyplo.net"
  github = "cyplo"
  twitter = "cyplo"
  linkedin = "cyplo"
  logo = "/images/avatar.png"