#!/bin/bash
set -e
sudo apt-get update
sudo apt-get install --fix-missing -y liblcms2-dev libfreetype6-dev libjpeg-dev libtiff-dev libwebp-dev libxslt1-dev libxml2-dev libyaml-dev libzmq-dev zlib1g-dev closure-compiler jpegoptim optipng yui-compressor python3-pip python-dev awscli
sudo pip3 install -U setuptools
sudo pip3 install -U virtualenvwrapper
sudo pip3 install -U wheel

virtualenv -p `which python3` venv
source venv/bin/activate
pip3 install -r requirements.txt

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" 
nvm install node
nvm use node
npm install cssnano-cli --global
