#!/bin/bash
set -e
sudo apt-get update
sudo apt-get install --fix-missing -y liblcms2-dev libfreetype6-dev libjpeg-dev libtiff-dev libwebp-dev libxslt1-dev libxml2-dev libyaml-dev libzmq-dev zlib1g-dev closure-compiler jpegoptim optipng yui-compressor python3-pip python-dev 
sudo pip3 install -U setuptools
sudo pip3 install -U virtualenvwrapper

virtualenv -p `which python3` venv
source venv/bin/activate
pip3 install -U -r requirements.txt

sudo npm install cssnano-cli --global
